import { Inter } from "next/font/google";
import Navegation from "./components/mainComponents/navegation";
import LogoModeling from "./components/subComponents/logoModeling";

// Css Styles
import "@/app/styles/navegation.css";
import "@/app/styles/division.css";
import "@/app/styles/principal.css";
import "@/app/styles/updates.css";
import "@/app/styles/registro.css";
import "@/app/styles/general.css";
import "@/app/styles/buttoner.css";

import Division from "./components/subComponents/division";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Generador de Estimacion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navBar__Container">
          <LogoModeling />
          <Navegation />
        </div>
        <Division />
        {children}
      </body>
    </html>
  );
}
